#pragma once

#ifdef DBCONNECTIONDLL_EXPORTS
#define DBCONNECTIONDLL_EXPORTS_DECLSPEC __declspec(dllexport)
#define EXPIMP_TEMPLATE
#else
#define DBCONNECTIONDLL_EXPORTS_DECLSPEC __declspec(dllimport)
#define EXPIMP_TEMPLATE extern
#endif


#define EXPORT_INTERFACE(type, ...) DBCONNECTIONDLL_EXPORTS_DECLSPEC type,##__VA_ARGS__
#define EXPORT_INTERFACE_CLASS(type, ...) EXPIMP_TEMPLATE template class DBCONNECTIONDLL_EXPORTS_DECLSPEC type,##__VA_ARGS__
#define EXPORT_INTERFACE_STRUCT(type, ...) EXPIMP_TEMPLATE template struct DBCONNECTIONDLL_EXPORTS_DECLSPEC type,##__VA_ARGS__



//EXPIMP_TEMPLATE  DBCONNECTIONDLL_EXPORTS_DECLSPEC std::wstring;